In [59]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from time import sleep
import pandas as pd

In [60]:
url_address = "https://www.prepostseo.com/tool/ru/fake-address-generator"

In [61]:
address_list = []
contact_list = []
countries = ["Finland", "France", "Germany", "Lithuania", "USA"]

In [62]:
address_headers = ["country", "city", "street", "house"]
contact_headers = ['email', 'phone']
header_id = pd.Series(range(1,36))
person_id_header = pd.concat([pd.Series(range(1,31)),pd.Series(range(1,5))]).sample(frac=1).reset_index(drop=True)

In [64]:
def create_profile(country):
        driver.execute_script(f"window.scrollTo(0, 300)") 
        sleep(2)
        country_button = driver.find_element(By.CSS_SELECTOR, f'[data-title="{country}"]')
        country_button.click()
        gen_button = driver.find_element(By.ID, 'calcRatio')
        gen_button.click()
        sleep(3)

In [65]:
def add_address():
    country = driver.find_element(By.ID, 'proCountry').text
    city = driver.find_element(By.ID, 'proCity').text
    address = driver.find_element(By.ID, 'proStreetAddress').text.split()
    
    for i in range(len(address)):
        address[i] = address[i].translate({ord(i): None for i in ',./'})
        
    print(address)
        
    if address[-1].replace('-', '').isalpha() == False:
        if address[0].replace('-', '').isalpha() == False: #building - street - appartment
            address_list.append([country,city,' '.join(address[1:-1]).replace('Apt.',''), address[0].translate({ord(i): None for i in 'abcdef'})])
        elif address[-2].translate({ord(i): None for i in '-,./'}).isalpha() == False: #street - building - appartment
            address_list.append([country,city,' '.join(address[:-2]), address[-2].translate({ord(i): None for i in 'abcdef'})])
        else:#street - building
            address_list.append([country,city,' '.join(address[:-1]), address[-1].translate({ord(i): None for i in 'abcdef'})])    
    elif address[0].translate({ord(i): None for i in '-,./'}).isalpha() == False: #building - street
        address_list.append([country,city,' '.join(address[1:]), address[0].translate({ord(i): None for i in 'abcdef'})])
    else:#street
        address_list.append([country,city,' '.join(address), ])

In [66]:
def add_contacts():
    email = driver.find_element(By.ID, 'proEmail').text
    phone = driver.find_element(By.ID, 'proPhone').text
    contact_list.append([email, phone])

In [67]:
driver_service = Service(executable_path = "/home/nadego/Documents/chromedriver/")
driver = webdriver.Chrome(service = driver_service)
driver.get(url_address)

In [68]:
for country in countries:    
    for i in range(7):
        create_profile(country)
        add_address()
        add_contacts()

['Lottatöyry', '6']
['Isoluomatöyry', '136', '654']
['Kerttulakaari', '3', '417']
['Jadessatie', '126', '663']
['Loviisakuja', '0542', '752']
['Nokkonenkatu', '638']
['Jaakkotie', '0']
['44', 'boulevard', 'de', 'Guichard']
['3', 'avenue', 'Dos', 'Santos']
['48', 'impasse', 'Stéphane', 'Lombard']
['8', 'impasse', 'Hernandez']
['9', 'avenue', 'Édouard', 'Mace']
['rue', 'de', 'Lenoir']
['impasse', 'Noel']
['Conny-Münch-Ring', '63']
['Fiedlerweg', '25']
['Steffenring', '2b']
['Andre-Fuhrmann-Weg', '9a']
['Niels-Riedl-Platz', '30a']
['Reuterallee', '986']
['Schüttestraße', '77a']
['63', 'Doe', 'prospektas']
['08', 'Doe', 'alėja']
['65', 'Doe', 'prospektas']
['79', 'Doe', 'prospektas']
['47', 'Doe', 'g']
['63', 'Doe', 'alėja']
['14', 'Doe', 'g']
['864', 'Lee', 'Parkway', 'Apt', '477']
['149', 'Gutmann', 'Spring']
['47221', 'Funk', 'Square']
['3573', 'Erich', 'Mission']
['8911', 'Marvin', 'Gardens', 'Apt', '863']
['674', 'Aileen', 'Mission']
['70428', 'Brown', 'Rest', 'Suite', '699']

In [69]:
address_table = pd.DataFrame(address_list, columns=address_headers)
address_table['address_id'] = header_id
address_table = pd.DataFrame(address_table, columns=['address_id', "country", "city", "street", "house"])
address_table

,address_id,country,city,street,house
0,1,Finland,Etelä-Peetu,Lottatöyry,6
1,2,Finland,Saulikylä,Isoluomatöyry,136
2,3,Finland,Reinikkalahti,Kerttulakaari,3
3,4,Finland,Etelä-Oskarikoski,Jadessatie,126
4,5,Finland,Uus-Iljamäki,Loviisakuja,0542
5,6,Finland,Etelä-Celina,Nokkonenkatu,638
6,7,Finland,Etelä-Samuel,Jaakkotie,0
7,8,France,Davidnec,boulevard de Guichard,44
8,9,France,Gaillard-la-Forêt,avenue Dos Santos,3
9,10,France,Lecomte-sur-Rolland,impasse Stéphane Lombard,48
10,11,France,Roussel-la-Forêt,impasse Hernandez,8
11,12,France,Laine,avenue Édouard Mace,9
12,13,France,Bouvier-sur-Bouvet,rue de Lenoir,None
13,14,France,Meunier,impasse Noel,None
14,15,Germany,Stade,Conny-Münch-Ring,63
15,16,Germany,Baunatal,Fiedlerweg,25
16,17,Germany,Cuxhaven,Steffenring,2
17,18,Germany,Arnstadt,Andre-Fuhrmann-Weg,9
18,19,Germany,Stralsund,Niels-Riedl-Platz,30
19,20,Germany,Schweinfurt,Reuterallee,986
20,21,Germany,Schönebeck,Schüttestraße,77
21,22,Lithuania,Utena,Doe prospektas,63
22,23,Lithuania,Tauragė,Doe alėja,08
23,24,Lithuania,Klaipėda,Doe prospektas,65
24,25,Lithuania,Marijampolė,Doe prospektas,79
25,26,Lithuania,Utena,Doe g,47
26,27,Lithuania,Mažeikiai,Doe alėja,63
27,28,Lithuania,Panevėžys,Doe g,14
28,29,USA,New Moshe,Lee Parkway Apt,864
29,30,USA,Kuhlmanborough,Gutmann Spring,149
30,31,USA,East Rigobertomouth,Funk Square,47221
31,32,USA,East Shaneland,Erich Mission,3573
32,33,USA,Turcotteshire,Marvin Gardens Apt,8911
33,34,USA,Leximouth,Aileen Mission,674
34,35,USA,South Rudolph,Brown Rest Suite,70428

In [70]:
address_table.to_csv('address_table', index=False)

In [71]:
contact_table = pd.DataFrame(contact_list, columns = contact_headers)
contact_table['contact_id'] = header_id
contact_table['persons_id'] = person_id_header
contact_table = pd.DataFrame(contact_table, columns = ['contact_id', 'email', 'phone', 'persons_id'])
contact_table

In [72]:
contact_table.to_csv('contact_table', index=False)